---

- name: Install bind
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - bind9
    - bind9utils
    - bind9-doc

- name: Configure BIND named.conf file
  template: 
    src: named.conf.j2
    dest: /etc/bind/named.conf
    owner: root
    group: bind
    mode: 0644

- name: Configure BIND to forward all DNS requests to the AWS VPC name server
  template: 
    src: named.conf.options.j2
    dest: /etc/bind/named.conf.options
    owner: root
    group: bind
    mode: 0644

- name: Restart and enable bind9
  service: name=bind9 state=restarted enabled=yes    
